# Set the block ID to monitor. Default is diamond ore (56).
mined_block_id: 56

# Customizable announcements. You can add more messages or modify existing ones.
announcements:
  - "&a{player} mined {amount} specified blocks!"
  - "&cWow, {player} found {amount} treasures by mining!"
